package uz.pravaimtihon.service.impl;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import uz.pravaimtihon.dto.request.ActivationCodeFilterRequest;
import uz.pravaimtihon.dto.request.ActivationCodeRequest;
import uz.pravaimtihon.dto.response.ActivationCodeResponse;
import uz.pravaimtihon.dto.response.ActivationCodeStatsResponse;
import uz.pravaimtihon.dto.response.PageResponse;
import uz.pravaimtihon.entity.ActivationCode;
import uz.pravaimtihon.entity.ActivationCodeStatus;
import uz.pravaimtihon.repository.ActivationCodeRepository;
import uz.pravaimtihon.service.ActivationCodeService;
import uz.pravaimtihon.service.Ed25519LicenseService;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
@Transactional(readOnly = true)
public class ActivationCodeServiceImpl implements ActivationCodeService {

    private static final int EXPIRING_THRESHOLD_DAYS = 3;

    private final ActivationCodeRepository repo;
    private final Ed25519LicenseService    licenseService;

    // ── Generate ──────────────────────────────────────────────────────────

    @Override
    @Transactional
    public ActivationCodeResponse generate(ActivationCodeRequest req, String operator) {
        // Validate date logic
        if (req.getEndDate().isBefore(req.getStartDate())) {
            throw new IllegalArgumentException("End date must not be before start date");
        }

        String token = licenseService.generateToken(
                req.getMachineId(), req.getStartDate(), req.getEndDate());

        // Ed25519 is deterministic: same machineId + same dates → same token every time.
        // If this exact token already exists (possibly from a previous generation), return it.
        if (repo.existsByLicenseKey(token)) {
            ActivationCode existing = repo.findByLicenseKey(token)
                    .orElseThrow(() -> new IllegalStateException("Concurrent insert race"));
            log.warn("Token already exists for machine='{}', returning existing record id={}", req.getMachineId(), existing.getId());
            return toResponse(existing);
        }

        ActivationCode code = ActivationCode.builder()
                .clientFirstName(trimOrNull(req.getClientFirstName()))
                .clientLastName(trimOrNull(req.getClientLastName()))
                .clientPhone(normalisePhone(req.getClientPhone()))
                .learningCenter(trimOrNull(req.getLearningCenter()))
                // Desktop app generates lowercase hex — store as-is so it matches the token JSON
                .machineId(req.getMachineId().toLowerCase().trim())
                .startDate(req.getStartDate())
                .endDate(req.getEndDate())
                .licenseKey(token)
                .status(ActivationCodeStatus.ACTIVE)
                .notes(req.getNotes())
                .build();

        code = repo.save(code);
        log.info("Activation code generated by {} for machine='{}', client='{}', expires={}",
                operator, code.getMachineId(),
                buildFullName(code.getClientFirstName(), code.getClientLastName()),
                code.getEndDate());

        return toResponse(code);
    }

    // ── List ──────────────────────────────────────────────────────────────

    @Override
    public PageResponse<ActivationCodeResponse> list(ActivationCodeFilterRequest f) {
        Sort sort = buildSort(f.getSortBy(), f.getSortDir());
        Pageable pageable = PageRequest.of(f.getPage(), f.getSize(), sort);

        String group  = f.getGroup();
        String search = blankToNull(f.getSearch());
        LocalDate today = LocalDate.now();
        LocalDate threshold = today.plusDays(EXPIRING_THRESHOLD_DAYS);

        Page<ActivationCode> page;

        if ("ACTIVE".equalsIgnoreCase(group)) {
            page = repo.findActiveGroup(threshold, search, pageable);
        } else if ("EXPIRING".equalsIgnoreCase(group)) {
            page = repo.findExpiringGroup(today, threshold, search, pageable);
        } else if ("EXPIRED".equalsIgnoreCase(group)) {
            page = repo.findExpiredGroup(today, search, pageable);
        } else if ("DEACTIVATED".equalsIgnoreCase(group)) {
            page = repo.findDeactivatedGroup(search, pageable);
        } else {
            // No group filter — use the flexible filtered query
            page = repo.findFiltered(
                    search,
                    f.getStatus(),
                    blankToNull(f.getGeneratedBy()),
                    f.getStartDateFrom(), f.getStartDateTo(),
                    f.getEndDateFrom(),   f.getEndDateTo(),
                    pageable
            );
        }

        List<ActivationCodeResponse> content = page.getContent()
                .stream()
                .map(this::toResponse)
                .toList();

        return PageResponse.<ActivationCodeResponse>builder()
                .content(content)
                .page(page.getNumber())
                .size(page.getSize())
                .totalElements(page.getTotalElements())
                .totalPages(page.getTotalPages())
                .first(page.isFirst())
                .last(page.isLast())
                .empty(page.isEmpty())
                .build();
    }

    // ── Get by ID ─────────────────────────────────────────────────────────

    @Override
    public ActivationCodeResponse getById(Long id) {
        return toResponse(findById(id));
    }

    // ── Deactivate ────────────────────────────────────────────────────────

    @Override
    @Transactional
    public ActivationCodeResponse deactivate(Long id, String reason, String operator) {
        ActivationCode code = findById(id);
        if (code.getStatus() == ActivationCodeStatus.DEACTIVATED) {
            throw new IllegalStateException("Code is already deactivated");
        }
        code.setStatus(ActivationCodeStatus.DEACTIVATED);
        if (reason != null && !reason.isBlank()) {
            String existing = code.getNotes() != null ? code.getNotes() : "";
            code.setNotes((existing.isBlank() ? "" : existing + "\n")
                    + "Deactivated by " + operator + ": " + reason.trim());
        }
        log.info("Activation code id={} deactivated by {}", id, operator);
        return toResponse(repo.save(code));
    }

    // ── Reactivate ────────────────────────────────────────────────────────

    @Override
    @Transactional
    public ActivationCodeResponse reactivate(Long id, String operator) {
        ActivationCode code = findById(id);
        if (code.getStatus() != ActivationCodeStatus.DEACTIVATED) {
            throw new IllegalStateException("Only DEACTIVATED codes can be reactivated");
        }
        if (code.getEndDate().isBefore(LocalDate.now())) {
            throw new IllegalStateException("Cannot reactivate an already-expired code");
        }
        code.setStatus(ActivationCodeStatus.ACTIVE);
        log.info("Activation code id={} reactivated by {}", id, operator);
        return toResponse(repo.save(code));
    }

    // ── Delete ────────────────────────────────────────────────────────────

    @Override
    @Transactional
    public void delete(Long id, String operator) {
        ActivationCode code = findById(id);
        if (code.getStatus() == ActivationCodeStatus.ACTIVE) {
            throw new IllegalStateException("Active codes cannot be deleted; deactivate first");
        }
        code.softDelete(operator);
        repo.save(code);
        log.info("Activation code id={} soft-deleted by {}", id, operator);
    }

    // ── Stats ─────────────────────────────────────────────────────────────

    @Override
    public ActivationCodeStatsResponse getStats() {
        LocalDate today     = LocalDate.now();
        LocalDate threshold = today.plusDays(EXPIRING_THRESHOLD_DAYS);

        return ActivationCodeStatsResponse.builder()
                .totalAll(repo.countAll())
                .totalActive(repo.countActive(threshold))
                .totalExpiring(repo.countExpiring(today, threshold))
                .totalExpired(repo.countExpired(today))
                .totalDeactivated(repo.countDeactivated())
                .build();
    }

    // ── Scheduled expiry sweep ────────────────────────────────────────────

    @Override
    @Transactional
    @Scheduled(cron = "0 5 0 * * *")   // 00:05 every day (server local time)
    public void expireOverdueCodes() {
        int updated = repo.markExpiredBatch(LocalDate.now());
        if (updated > 0) {
            log.info("Expiry sweep: marked {} activation codes as EXPIRED", updated);
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private ActivationCode findById(Long id) {
        return repo.findById(id)
                .filter(c -> !Boolean.TRUE.equals(c.getDeleted()))
                .orElseThrow(() -> new jakarta.persistence.EntityNotFoundException(
                        "Activation code not found: " + id));
    }

    ActivationCodeResponse toResponse(ActivationCode ac) {
        LocalDate today = LocalDate.now();
        LocalDate threshold = today.plusDays(EXPIRING_THRESHOLD_DAYS);

        String displayGroup;
        if (ac.getStatus() == ActivationCodeStatus.DEACTIVATED) {
            displayGroup = "DEACTIVATED";
        } else if (ac.getEndDate().isBefore(today)) {
            displayGroup = "EXPIRED";
        } else if (ac.getEndDate().isBefore(threshold)) {
            displayGroup = "EXPIRING";
        } else {
            displayGroup = "ACTIVE";
        }

        long daysUntil = ChronoUnit.DAYS.between(today, ac.getEndDate());

        return ActivationCodeResponse.builder()
                .id(ac.getId())
                .clientFirstName(ac.getClientFirstName())
                .clientLastName(ac.getClientLastName())
                .clientFullName(buildFullName(ac.getClientFirstName(), ac.getClientLastName()))
                .clientPhone(ac.getClientPhone())
                .learningCenter(ac.getLearningCenter())
                .machineId(ac.getMachineId())
                .startDate(ac.getStartDate())
                .endDate(ac.getEndDate())
                .licenseKey(ac.getLicenseKey())
                .status(ac.getStatus())
                .displayGroup(displayGroup)
                .daysUntilExpiry(daysUntil)
                .notes(ac.getNotes())
                .generatedBy(ac.getCreatedBy())
                .createdAt(ac.getCreatedAt())
                .updatedAt(ac.getUpdatedAt())
                .build();
    }

    private static Sort buildSort(String sortBy, String sortDir) {
        Sort.Direction dir = "asc".equalsIgnoreCase(sortDir)
                ? Sort.Direction.ASC : Sort.Direction.DESC;
        String field = switch (sortBy == null ? "" : sortBy) {
            case "endDate"       -> "endDate";
            case "clientLastName"-> "clientLastName";
            case "status"        -> "status";
            default              -> "createdAt";
        };
        return Sort.by(dir, field);
    }

    private static String blankToNull(String s) {
        return (s == null || s.isBlank()) ? null : s.trim();
    }

    /** Returns null for null/blank input, trimmed value otherwise. */
    private static String trimOrNull(String s) {
        return (s == null || s.isBlank()) ? null : s.trim();
    }

    /**
     * Normalises a phone number: removes leading/trailing whitespace and
     * collapses internal spaces.  Returns null for null or blank input.
     */
    private static String normalisePhone(String phone) {
        if (phone == null || phone.isBlank()) return null;
        return phone.trim().replaceAll("\\s+", "");
    }

    /**
     * Builds a display name from optional first/last name parts.
     * Returns "—" if both are absent.
     */
    private static String buildFullName(String first, String last) {
        String f = (first != null && !first.isBlank()) ? first.trim() : null;
        String l = (last  != null && !last.isBlank())  ? last.trim()  : null;
        if (f != null && l != null) return f + " " + l;
        if (f != null) return f;
        if (l != null) return l;
        return "—";
    }
}
