package uz.pravaimtihon.service.impl;

import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import uz.pravaimtihon.dto.request.ActivationCodeFilterRequest;
import uz.pravaimtihon.dto.request.ActivationCodeRequest;
import uz.pravaimtihon.dto.response.ActivationCodeResponse;
import uz.pravaimtihon.dto.response.ActivationCodeStatsResponse;
import uz.pravaimtihon.dto.response.PageResponse;
import uz.pravaimtihon.entity.ActivationCode;
import uz.pravaimtihon.entity.ActivationCodeStatus;
import uz.pravaimtihon.entity.Computer;
import uz.pravaimtihon.entity.LearningCenter;
import uz.pravaimtihon.repository.ActivationCodeRepository;
import uz.pravaimtihon.repository.ComputerRepository;
import uz.pravaimtihon.service.ActivationCodeService;
import uz.pravaimtihon.service.Ed25519LicenseService;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
@Transactional(readOnly = true)
public class ActivationCodeServiceImpl implements ActivationCodeService {

    private static final int EXPIRING_THRESHOLD_DAYS = 3;

    private final ActivationCodeRepository repo;
    private final ComputerRepository       computerRepo;
    private final Ed25519LicenseService    licenseService;

    // ── Generate ──────────────────────────────────────────────────────────

    @Override
    @Transactional
    public ActivationCodeResponse generate(ActivationCodeRequest req, String operator) {
        // Validate date logic
        if (req.getEndDate().isBefore(req.getStartDate())) {
            throw new IllegalArgumentException("End date must not be before start date");
        }

        // Resolve computer (required)
        Computer computer = computerRepo.findById(req.getComputerId())
                .filter(c -> !Boolean.TRUE.equals(c.getDeleted()))
                .orElseThrow(() -> new EntityNotFoundException(
                        "Computer not found: " + req.getComputerId()));

        String machineId = computer.getMachineId().toLowerCase().trim();

        String token = licenseService.generateToken(machineId, req.getStartDate(), req.getEndDate());

        // Ed25519 is deterministic: same machineId + same dates → same token every time.
        // If this exact token already exists, return the existing record.
        if (repo.existsByLicenseKey(token)) {
            ActivationCode existing = repo.findByLicenseKey(token)
                    .orElseThrow(() -> new IllegalStateException("Concurrent insert race"));
            log.warn("Token already exists for machine='{}', returning existing record id={}",
                    machineId, existing.getId());
            return toResponse(existing);
        }

        ActivationCode code = ActivationCode.builder()
                .computer(computer)
                .machineId(machineId)
                .startDate(req.getStartDate())
                .endDate(req.getEndDate())
                .licenseKey(token)
                .status(ActivationCodeStatus.ACTIVE)
                .notes(trimOrNull(req.getNotes()))
                .build();

        code = repo.save(code);
        log.info("Activation code generated by '{}' for computer='{}' (machine='{}'), lc='{}', expires={}",
                operator,
                computer.getName(),
                machineId,
                computer.getLearningCenter() != null ? computer.getLearningCenter().getName() : "—",
                code.getEndDate());

        return toResponse(code);
    }

    // ── List ──────────────────────────────────────────────────────────────

    @Override
    public PageResponse<ActivationCodeResponse> list(ActivationCodeFilterRequest f) {
        Sort sort = buildSort(f.getSortBy(), f.getSortDir());
        Pageable pageable = PageRequest.of(f.getPage(), f.getSize(), sort);

        String    group     = f.getGroup();
        String    search    = blankToNull(f.getSearch());
        Long      compId    = f.getComputerId();
        Long      lcId      = f.getLearningCenterId();
        LocalDate today     = LocalDate.now();
        LocalDate threshold = today.plusDays(EXPIRING_THRESHOLD_DAYS);

        Page<ActivationCode> page;

        if ("ACTIVE".equalsIgnoreCase(group)) {
            page = repo.findActiveGroup(threshold, compId, lcId, search, pageable);
        } else if ("EXPIRING".equalsIgnoreCase(group)) {
            page = repo.findExpiringGroup(today, threshold, compId, lcId, search, pageable);
        } else if ("EXPIRED".equalsIgnoreCase(group)) {
            page = repo.findExpiredGroup(today, compId, lcId, search, pageable);
        } else if ("DEACTIVATED".equalsIgnoreCase(group)) {
            page = repo.findDeactivatedGroup(compId, lcId, search, pageable);
        } else {
            page = repo.findFiltered(
                    compId,
                    lcId,
                    search,
                    f.getStatus(),
                    blankToNull(f.getGeneratedBy()),
                    f.getStartDateFrom(), f.getStartDateTo(),
                    f.getEndDateFrom(),   f.getEndDateTo(),
                    pageable
            );
        }

        List<ActivationCodeResponse> content = page.getContent()
                .stream()
                .map(this::toResponse)
                .toList();

        return PageResponse.<ActivationCodeResponse>builder()
                .content(content)
                .page(page.getNumber())
                .size(page.getSize())
                .totalElements(page.getTotalElements())
                .totalPages(page.getTotalPages())
                .first(page.isFirst())
                .last(page.isLast())
                .empty(page.isEmpty())
                .build();
    }

    // ── Get by ID ─────────────────────────────────────────────────────────

    @Override
    public ActivationCodeResponse getById(Long id) {
        return toResponse(findById(id));
    }

    // ── Deactivate ────────────────────────────────────────────────────────

    @Override
    @Transactional
    public ActivationCodeResponse deactivate(Long id, String reason, String operator) {
        ActivationCode code = findById(id);
        if (code.getStatus() == ActivationCodeStatus.DEACTIVATED) {
            throw new IllegalStateException("Code is already deactivated");
        }
        code.setStatus(ActivationCodeStatus.DEACTIVATED);
        if (reason != null && !reason.isBlank()) {
            String existing = code.getNotes() != null ? code.getNotes() : "";
            code.setNotes((existing.isBlank() ? "" : existing + "\n")
                    + "Deactivated by " + operator + ": " + reason.trim());
        }
        log.info("Activation code id={} deactivated by '{}'", id, operator);
        return toResponse(repo.save(code));
    }

    // ── Reactivate ────────────────────────────────────────────────────────

    @Override
    @Transactional
    public ActivationCodeResponse reactivate(Long id, String operator) {
        ActivationCode code = findById(id);
        if (code.getStatus() != ActivationCodeStatus.DEACTIVATED) {
            throw new IllegalStateException("Only DEACTIVATED codes can be reactivated");
        }
        if (code.getEndDate().isBefore(LocalDate.now())) {
            throw new IllegalStateException("Cannot reactivate an already-expired code");
        }
        code.setStatus(ActivationCodeStatus.ACTIVE);
        log.info("Activation code id={} reactivated by '{}'", id, operator);
        return toResponse(repo.save(code));
    }

    // ── Delete ────────────────────────────────────────────────────────────

    @Override
    @Transactional
    public void delete(Long id, String operator) {
        ActivationCode code = findById(id);
        if (code.getStatus() == ActivationCodeStatus.ACTIVE) {
            throw new IllegalStateException("Active codes cannot be deleted; deactivate first");
        }
        code.softDelete(operator);
        repo.save(code);
        log.info("Activation code id={} soft-deleted by '{}'", id, operator);
    }

    // ── Stats ─────────────────────────────────────────────────────────────

    @Override
    public ActivationCodeStatsResponse getStats() {
        LocalDate today     = LocalDate.now();
        LocalDate threshold = today.plusDays(EXPIRING_THRESHOLD_DAYS);

        return ActivationCodeStatsResponse.builder()
                .total(repo.countAll())
                .active(repo.countActive(threshold))
                .expiring(repo.countExpiring(today, threshold))
                .expired(repo.countExpired(today))
                .deactivated(repo.countDeactivated())
                .build();
    }

    // ── Scheduled expiry sweep ────────────────────────────────────────────

    @Override
    @Transactional
    @Scheduled(cron = "0 5 0 * * *")   // 00:05 every day (UTC)
    public void expireOverdueCodes() {
        int updated = repo.markExpiredBatch(LocalDate.now());
        if (updated > 0) {
            log.info("Expiry sweep: marked {} activation codes as EXPIRED", updated);
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private ActivationCode findById(Long id) {
        return repo.findById(id)
                .filter(c -> !Boolean.TRUE.equals(c.getDeleted()))
                .orElseThrow(() -> new EntityNotFoundException(
                        "Activation code not found: " + id));
    }

    ActivationCodeResponse toResponse(ActivationCode ac) {
        LocalDate today     = LocalDate.now();
        LocalDate threshold = today.plusDays(EXPIRING_THRESHOLD_DAYS);

        String displayGroup;
        if (ac.getStatus() == ActivationCodeStatus.DEACTIVATED) {
            displayGroup = "DEACTIVATED";
        } else if (ac.getEndDate().isBefore(today)) {
            displayGroup = "EXPIRED";
        } else if (ac.getEndDate().isBefore(threshold)) {
            displayGroup = "EXPIRING";
        } else {
            displayGroup = "ACTIVE";
        }

        long daysUntil = ChronoUnit.DAYS.between(today, ac.getEndDate());

        // Extract computer and learning center info
        Computer       comp = ac.getComputer();
        LearningCenter lc   = comp != null ? comp.getLearningCenter() : null;

        return ActivationCodeResponse.builder()
                .id(ac.getId())
                // Computer fields
                .computerId(comp != null ? comp.getId() : null)
                .computerName(comp != null ? comp.getName() : null)
                .macAddress(comp != null ? comp.getMacAddress() : null)
                .deviceId(comp != null ? comp.getDeviceId() : null)
                // Learning center (via computer)
                .learningCenterId(lc != null ? lc.getId() : null)
                .learningCenterName(lc != null ? lc.getName() : null)
                // Token fields
                .machineId(ac.getMachineId())
                .startDate(ac.getStartDate())
                .endDate(ac.getEndDate())
                .licenseKey(ac.getLicenseKey())
                // Status
                .status(ac.getStatus())
                .displayGroup(displayGroup)
                .daysUntilExpiry(daysUntil)
                // Metadata
                .notes(ac.getNotes())
                .generatedBy(ac.getCreatedBy())
                .createdAt(ac.getCreatedAt())
                .updatedAt(ac.getUpdatedAt())
                .build();
    }

    private static Sort buildSort(String sortBy, String sortDir) {
        Sort.Direction dir = "asc".equalsIgnoreCase(sortDir)
                ? Sort.Direction.ASC : Sort.Direction.DESC;
        String field = switch (sortBy == null ? "" : sortBy) {
            case "endDate"   -> "endDate";
            case "startDate" -> "startDate";
            case "status"    -> "status";
            default          -> "createdAt";
        };
        return Sort.by(dir, field);
    }

    private static String blankToNull(String s) {
        return (s == null || s.isBlank()) ? null : s.trim();
    }

    private static String trimOrNull(String s) {
        return (s == null || s.isBlank()) ? null : s.trim();
    }
}
