-- Fix topics multi-language names (uzc, ru, en)
BEGIN;
UPDATE topics SET name_uzc = 'Умумий қоидалар', name_ru = 'Общие положения', name_en = 'General Provisions' WHERE id = 1;
UPDATE topics SET name_uzc = 'Ҳайдовчиларнинг умумий вазифалари', name_ru = 'Общие обязанности водителей', name_en = 'General Duties of Drivers' WHERE id = 2;
UPDATE topics SET name_uzc = 'Пиёдаларнинг умумий вазифалари', name_ru = 'Обязанности пешеходов', name_en = 'Duties of Pedestrians' WHERE id = 3;
UPDATE topics SET name_uzc = 'Махсус транспорт воситаларининг имтиёзлари', name_ru = 'Приоритет специальных транспортных средств', name_en = 'Priority of Special Vehicles' WHERE id = 4;
UPDATE topics SET name_uzc = 'Огоҳлантирувчи белгилар', name_ru = 'Предупреждающие знаки', name_en = 'Warning Signs' WHERE id = 5;
UPDATE topics SET name_uzc = 'Имтиёз белгилари', name_ru = 'Знаки приоритета', name_en = 'Priority Signs' WHERE id = 6;
UPDATE topics SET name_uzc = 'Тақиқловчи белгилар', name_ru = 'Запрещающие знаки', name_en = 'Prohibitory Signs' WHERE id = 7;
UPDATE topics SET name_uzc = 'Буюрувчи белгилар', name_ru = 'Предписывающие знаки', name_en = 'Mandatory Signs' WHERE id = 8;
UPDATE topics SET name_uzc = 'Ахборот-кўрсаткич белгилари', name_ru = 'Информационно-указательные знаки', name_en = 'Information and Direction Signs' WHERE id = 9;
UPDATE topics SET name_uzc = 'Сервис белгилари', name_ru = 'Знаки сервиса', name_en = 'Service Signs' WHERE id = 10;
UPDATE topics SET name_uzc = 'Қўшимча ахборот белгилари', name_ru = 'Знаки дополнительной информации (таблички)', name_en = 'Additional Information Signs' WHERE id = 11;
UPDATE topics SET name_uzc = 'Ётиқ чизиқлар', name_ru = 'Горизонтальная разметка', name_en = 'Horizontal Markings' WHERE id = 12;
UPDATE topics SET name_uzc = 'Тик чизиқлар', name_ru = 'Вертикальная разметка', name_en = 'Vertical Markings' WHERE id = 13;
UPDATE topics SET name_uzc = 'Светофор ишоралари', name_ru = 'Сигналы светофора', name_en = 'Traffic Light Signals' WHERE id = 14;
UPDATE topics SET name_uzc = 'Тартибга солувчининг ишоралари', name_ru = 'Сигналы регулировщика', name_en = 'Signals of Traffic Controller' WHERE id = 15;
UPDATE topics SET name_uzc = 'Огоҳлантирувчи ва авария ишоралари', name_ru = 'Предупредительные и аварийные сигналы', name_en = 'Warning and Hazard Signals' WHERE id = 16;
UPDATE topics SET name_uzc = 'Ҳаракатланишни бошлаш, манёвр қилиш', name_ru = 'Начало движения, маневрирование', name_en = 'Starting Movement, Maneuvering' WHERE id = 17;
UPDATE topics SET name_uzc = 'Йўлнинг қатнов қисмида транспорт воситаларининг жойлашуви', name_ru = 'Расположение транспортных средств на проезжей части', name_en = 'Position of Vehicles on Roadway' WHERE id = 18;
UPDATE topics SET name_uzc = 'Ҳаракатланиш тезлиги', name_ru = 'Скорость движения', name_en = 'Speed of Movement' WHERE id = 19;
UPDATE topics SET name_uzc = 'Қувиб ўтиш', name_ru = 'Обгон', name_en = 'Overtaking' WHERE id = 20;
UPDATE topics SET name_uzc = 'Тўхташ ва тўхтаб туриш', name_ru = 'Остановка и стоянка', name_en = 'Stopping and Parking' WHERE id = 21;
UPDATE topics SET name_uzc = 'Чорраҳаларда ҳаракатланиш', name_ru = 'Проезд перекрёстков', name_en = 'Intersections' WHERE id = 22;
UPDATE topics SET name_uzc = 'Тартибга солинган чорраҳалар', name_ru = 'Регулируемые перекрёстки', name_en = 'Regulated Intersections' WHERE id = 23;
UPDATE topics SET name_uzc = 'Тартибга солинмаган чорраҳалар (асосий йўл тўғри йўналишда)', name_ru = 'Нерегулируемые перекрёстки (главная дорога в прямом направлении)', name_en = 'Unregulated Intersections (Main Road Straight)' WHERE id = 24;
UPDATE topics SET name_uzc = 'Тартибга солинмаган тенг аҳамиятли чорраҳалар', name_ru = 'Нерегулируемые перекрёстки равнозначных дорог', name_en = 'Unregulated Intersections of Equivalent Roads' WHERE id = 25;
UPDATE topics SET name_uzc = 'Тартибга солинмаган чорраҳалар (асосий йўл йўналиши ўзгариши)', name_ru = 'Нерегулируемые перекрёстки (изменение направления главной дороги)', name_en = 'Unregulated Intersections (Main Road Direction Change)' WHERE id = 26;
UPDATE topics SET name_uzc = 'Пиёдалар ўтиш жойлари ва йўналишли транспорт воситалари бекатлари', name_ru = 'Пешеходные переходы и остановки маршрутных транспортных средств', name_en = 'Pedestrian Crossings and Transit Stops' WHERE id = 27;
UPDATE topics SET name_uzc = 'Темир йўл кесишмалари орқали ҳаракатланиш', name_ru = 'Движение через железнодорожные пути', name_en = 'Level Crossings' WHERE id = 28;
UPDATE topics SET name_uzc = 'Автомагистралларда ҳаракатланиш', name_ru = 'Движение по автомагистралям', name_en = 'Motorway Driving' WHERE id = 29;
UPDATE topics SET name_uzc = 'Турар жой даҳаларида ҳаракатланиш', name_ru = 'Движение в жилых зонах', name_en = 'Residential Zones' WHERE id = 30;
UPDATE topics SET name_uzc = 'Тик баландлик ва нишабликларда ҳаракатланиш', name_ru = 'Движение на крутых спусках и подъёмах', name_en = 'Driving on Steep Slopes' WHERE id = 31;
UPDATE topics SET name_uzc = 'Йўналишли транспорт воситаларининг имтиёзлари', name_ru = 'Приоритет маршрутных транспортных средств', name_en = 'Priority of Route Vehicles' WHERE id = 32;
UPDATE topics SET name_uzc = 'Ташқи ёритиш асбобларидан фойдаланиш', name_ru = 'Пользование внешними световыми приборами', name_en = 'Use of External Lighting' WHERE id = 33;
UPDATE topics SET name_uzc = 'Механик транспорт воситаларини шатакка олиш', name_ru = 'Буксировка механических транспортных средств', name_en = 'Towing Mechanical Vehicles' WHERE id = 34;
UPDATE topics SET name_uzc = 'Транспорт воситаларини бошқаришни ўргатиш', name_ru = 'Обучение вождению транспортных средств', name_en = 'Driver Training' WHERE id = 35;
UPDATE topics SET name_uzc = 'Одам ташиш', name_ru = 'Перевозка людей', name_en = 'Passenger Transport' WHERE id = 36;
UPDATE topics SET name_uzc = 'Юк ташиш', name_ru = 'Перевозка грузов', name_en = 'Cargo Transport' WHERE id = 37;
UPDATE topics SET name_uzc = 'Велосипед, мопед ва аравалар ҳаракатланишига ҳамда ҳайвонларни ҳайдаб ўтишга доир қўшимча талаблар', name_ru = 'Дополнительные требования к движению велосипедов, мопедов, гужевых повозок и прогону животных', name_en = 'Rules for Bicycles, Mopeds and Carts' WHERE id = 38;
UPDATE topics SET name_uzc = 'Таниқли белгилар', name_ru = 'Опознавательные знаки транспортных средств', name_en = 'Identification Signs' WHERE id = 39;
UPDATE topics SET name_uzc = 'Транспорт воситаларидан фойдаланишни тақиқловчи шартлар', name_ru = 'Условия, запрещающие эксплуатацию транспортных средств', name_en = 'Conditions Prohibiting Vehicle Operation' WHERE id = 40;
UPDATE topics SET name_uzc = 'Ҳаракат хавфсизлиги асослари', name_ru = 'Основы безопасности движения', name_en = 'Traffic Safety Basics' WHERE id = 41;
UPDATE topics SET name_uzc = 'Биринчи тиббий ёрдам', name_ru = 'Первая медицинская помощь', name_en = 'First Medical Aid' WHERE id = 42;
UPDATE topics SET name_uzc = 'Мураккаб саволлар', name_ru = 'Сложные вопросы', name_en = 'Complex Questions' WHERE id = 43;
UPDATE topics SET name_uzc = 'Рақамли саволлар', name_ru = 'Цифровые вопросы', name_en = 'Numerical Questions' WHERE id = 44;
COMMIT;
