import type { ExerciseDefinition } from "../types";

export const EXERCISE_REGISTRY: ExerciseDefinition[] = [
  {
    number: 1,
    code: "START",
    title: {
      uzl: "1. Harakatni boshlash (START)",
      uzc: "1. Ҳаракатни бошлаш (СТАРТ)",
      ru: "1. Начало движения (СТАРТ)",
    },
    description: {
      uzl: "Xavfsizlik kamarini taqing, chiroqlarni yoqing, chap burilish signali bilan silliq qo'zg'aling.",
      uzc: "Хавфсизлик камарини тақинг, чироқларни ёқинг, чап бурилиш сигнали билан силлиқ қўзғалинг.",
      ru: "Пристегните ремень, включите свет фар, левый поворотник и плавно начните движение.",
    },
    instructorGuide: {
      uzl: "Xavfsizlik kamarini taqing, chiroqlarni yoqing va harakatni boshlang.",
      uzc: "Хавфсизлик камарини тақинг, чироқларни ёқинг ва ҳаракатни бошланг.",
      ru: "Пристегните ремень безопасности, включите фары и начните движение.",
    },
    timeLimitSeconds: 60,
    maxSpeedKmh: 20,
    maxPenaltyAllowed: 20,
    startX: 60,
    startY: 440,
    startRotation: 0,
    targetX: 140,
    targetY: 440,
    sensorZone: { minX: 40, maxX: 150, minY: 410, maxY: 470 },
    helperPath: [
      { x: 60, y: 440 },
      { x: 100, y: 440 },
      { x: 140, y: 440 },
    ],
    stopLines: [{ x1: 50, y1: 420, x2: 50, y2: 460 }],
  },
  {
    number: 2,
    code: "PEDESTRIAN_CROSSING",
    title: {
      uzl: "2. Piyodalar o'tish joyi",
      uzc: "2. Пиёдалар ўтиш жойи",
      ru: "2. Пешеходный переход",
    },
    description: {
      uzl: "Piyodalar o'tish joyi oldida STOP chizig'ini bosmasdan to'xtang va piyodaga yo'l bering.",
      uzc: "Пиёдалар ўтиш жойи олдида СТОП чизиғини босмасдан тўхтанг ва пиёдага йўл беринг.",
      ru: "Остановитесь перед стоп-линией пешеходного перехода, не наезжая на разметку, и уступите дорогу пешеходу.",
    },
    instructorGuide: {
      uzl: "Piyodalar o'tish joyiga yaqinlashyapsiz. Stop-chiziqda to'xtang.",
      uzc: "Пиёдалар ўтиш жойига яқинлашяпсиз. Стоп-чизиқда тўхтанг.",
      ru: "Приближаетесь к пешеходному переходу. Остановитесь у стоп-линии.",
    },
    timeLimitSeconds: 50,
    maxSpeedKmh: 20,
    maxPenaltyAllowed: 20,
    startX: 150,
    startY: 440,
    startRotation: 0,
    targetX: 240,
    targetY: 440,
    sensorZone: { minX: 140, maxX: 250, minY: 410, maxY: 470 },
    helperPath: [
      { x: 150, y: 440 },
      { x: 195, y: 440 },
      { x: 240, y: 440 },
    ],
    stopLines: [{ x1: 190, y1: 420, x2: 190, y2: 460 }],
  },
  {
    number: 3,
    code: "ESTAKADA",
    title: {
      uzl: "3. Estakada (Tepalikka chiqish va to'xtash)",
      uzc: "3. Эстакада (Тепаликка чиқиш ва тўхташ)",
      ru: "3. Эстакада (Остановка и трогание на подъеме)",
    },
    description: {
      uzl: "16% qiyalikda STOP chizig'ida to'xtab, qo'l tormozini torting. Orqaga 20 sm dan ortiq sirpanmasdan qo'zg'aling.",
      uzc: "16% қияликда СТОП чизиғида тўхтаб, қўл тормозини тортинг. Орқага 20 см дан ортиқ сирпанмасдан қўзғалинг.",
      ru: "Остановитесь на подъеме 16% у стоп-линии, затяните ручник. Троньтесь без отката назад более 20 см.",
    },
    instructorGuide: {
      uzl: "Oldinda estakada. Stop-chiziqda to'xtang va qo'l tormozini torting. Orqaga sirpanmasdan harakatlaning.",
      uzc: "Олдинда эстакада. Стоп-чизиқда тўхтанг ва қўл тормозини тортинг. Орқага сирпанмасдан ҳаракатланинг.",
      ru: "Впереди эстакада. Остановитесь у стоп-линии и затяните ручник. Трогайтесь без отката.",
    },
    timeLimitSeconds: 70,
    maxSpeedKmh: 15,
    maxPenaltyAllowed: 20,
    hasIncline: true,
    startX: 250,
    startY: 440,
    startRotation: 0,
    targetX: 350,
    targetY: 440,
    sensorZone: { minX: 240, maxX: 360, minY: 410, maxY: 470 },
    helperPath: [
      { x: 250, y: 440 },
      { x: 300, y: 440 },
      { x: 350, y: 440 },
    ],
    stopLines: [{ x1: 295, y1: 420, x2: 295, y2: 460 }],
  },
  {
    number: 4,
    code: "CORRIDOR_TURNS",
    title: {
      uzl: "4. 90° Burchak ostida burilishlar",
      uzc: "4. 90° Бурчак остида бурилишлар",
      ru: "4. Повороты под углом 90 градусов",
    },
    description: {
      uzl: "Tor yo'lakda o'ngga va chapga 90 gradus burilishlarni bordyur va chiziqlarni bosmasdan bajaring.",
      uzc: "Тор йўлакда ўнгга ва чапга 90 градус бурилишларни бордюр ва чизиқларни босмасдан бажаринг.",
      ru: "Выполните повороты на 90 градусов направо и налево в узком коридоре, не задевая границы.",
    },
    instructorGuide: {
      uzl: "Tor yo'lak. Tezlikni pasaytiring va rulni sekin buring.",
      uzc: "Тор йўлак. Тезликни пасайтиринг ва рулни секин буринг.",
      ru: "Узкий коридор. Снизьте скорость и аккуратно поворачивайте руль.",
    },
    timeLimitSeconds: 80,
    maxSpeedKmh: 15,
    maxPenaltyAllowed: 20,
    startX: 360,
    startY: 430,
    startRotation: -Math.PI / 2,
    targetX: 430,
    targetY: 340,
    sensorZone: { minX: 350, maxX: 450, minY: 320, maxY: 450 },
    helperPath: [
      { x: 370, y: 430 },
      { x: 370, y: 380 },
      { x: 420, y: 380 },
      { x: 420, y: 340 },
    ],
  },
  {
    number: 5,
    code: "SLALOM",
    title: {
      uzl: "5. Ilon izi (Zmeyka / Slalom)",
      uzc: "5. Илон изи (Змейка / Слалом)",
      ru: "5. Змейка (Слалом)",
    },
    description: {
      uzl: "5 ta to'siq konuslarini navbatma-navbat aylanib o'ting. Konuslarni urmang va zonadan chiqmang.",
      uzc: "5 та тўсиқ конусларини навбатма-навбат айланиб ўтинг. Конусларни урманг ва зонадан чиқманг.",
      ru: "Обогните 5 разметочных конусов поочередно. Не сбивайте конусы и не выезжайте за границы.",
    },
    instructorGuide: {
      uzl: "Zmeyka mashqi. Konuslarni aylanib o'ting, masofani saqlang.",
      uzc: "Змейка машқи. Конусларни айланиб ўтинг, масофани сақланг.",
      ru: "Упражнение Змейка. Огибайте конусы, соблюдая дистанцию.",
    },
    timeLimitSeconds: 75,
    maxSpeedKmh: 15,
    maxPenaltyAllowed: 20,
    startX: 430,
    startY: 330,
    startRotation: -Math.PI / 2,
    targetX: 520,
    targetY: 210,
    sensorZone: { minX: 410, maxX: 540, minY: 190, maxY: 340 },
    cones: [
      { x: 445, y: 300, radius: 6 },
      { x: 465, y: 275, radius: 6 },
      { x: 485, y: 250, radius: 6 },
      { x: 505, y: 225, radius: 6 },
    ],
    helperPath: [
      { x: 430, y: 320 },
      { x: 460, y: 295 },
      { x: 450, y: 265 },
      { x: 490, y: 240 },
      { x: 515, y: 210 },
    ],
  },
  {
    number: 6,
    code: "INTERSECTION",
    title: {
      uzl: "6. Tartibga solingan chorraha",
      uzc: "6. Тартибга солинган чорраҳа",
      ru: "6. Регулируемый перекресток",
    },
    description: {
      uzl: "Svetoforning yashil chirog'ida harakatlaning, qizil chiroqda Stop-chiziq oldida to'xtang.",
      uzc: "Светофорнинг яшил чироғида ҳаракатланинг, қизил чироқда Стоп-чизиқ олдида тўхтанг.",
      ru: "Двигайтесь на зеленый сигнал светофора, при красном остановитесь перед стоп-линией.",
    },
    instructorGuide: {
      uzl: "Chorraha oldidasiz. Svetofor signallariga qat'iy rioya qiling.",
      uzc: "Чорраҳа олдидасиз. Светофор сигналларига қатъий риоя қилинг.",
      ru: "Вы перед перекрестком. Строго соблюдайте сигналы светофора.",
    },
    timeLimitSeconds: 60,
    maxSpeedKmh: 20,
    maxPenaltyAllowed: 20,
    hasTrafficLight: true,
    startX: 520,
    startY: 200,
    startRotation: -Math.PI / 2,
    targetX: 520,
    targetY: 90,
    sensorZone: { minX: 490, maxX: 550, minY: 80, maxY: 210 },
    stopLines: [{ x1: 495, y1: 150, x2: 545, y2: 150 }],
    helperPath: [
      { x: 520, y: 200 },
      { x: 520, y: 150 },
      { x: 520, y: 90 },
    ],
  },
  {
    number: 7,
    code: "GARAGE",
    title: {
      uzl: "7. Boksga kirish (90° Garaj)",
      uzc: "7. Боксга кириш (90° Гараж)",
      ru: "7. Въезд в бокс задним ходом (Гараж 90°)",
    },
    description: {
      uzl: "Orqa uzatma (R) bilan boksga 90 gradus burilib kiring va chegara chiziqlariga tegmang.",
      uzc: "Орқа узатма (R) билан боксга 90 градус бурилиб киринг ва чегара чизиқларига тегманг.",
      ru: "Въедьте в бокс задним ходом под углом 90 градусов, не задевая границы разметки.",
    },
    instructorGuide: {
      uzl: "Orqa uzatmani yoqing. Ko'zgularga qarab boksga kiring.",
      uzc: "Орқа узатмани ёқинг. Кўзгуларга қараб боксга киринг.",
      ru: "Включите заднюю передачу. Ориентируясь по зеркалам, заезжайте в бокс.",
    },
    timeLimitSeconds: 90,
    maxSpeedKmh: 10,
    maxPenaltyAllowed: 20,
    startX: 510,
    startY: 85,
    startRotation: Math.PI,
    targetX: 420,
    targetY: 85,
    sensorZone: { minX: 400, maxX: 520, minY: 60, maxY: 130 },
    helperPath: [
      { x: 510, y: 85 },
      { x: 470, y: 85 },
      { x: 430, y: 85 },
    ],
  },
  {
    number: 8,
    code: "RAILWAY_CROSSING",
    title: {
      uzl: "8. Temir yo'l kesishmasi",
      uzc: "8. Темир йўл кесишмаси",
      ru: "8. Железнодорожный переезд",
    },
    description: {
      uzl: "Shlagbaum va svetofor signallari oldida to'xtang. Poyezd o'tgach harakatni davom ettiring.",
      uzc: "Шлагбаум ва светофор сигналлари олдида тўхтанг. Поезд ўтгач ҳаракатни давом эттиринг.",
      ru: "Остановитесь перед шлагбаумом и светофором переезда. Продолжайте движение после разрешающего сигнала.",
    },
    instructorGuide: {
      uzl: "Temir yo'l kesishmasi. To'xtang va xavfsizlikka ishonch hosil qiling.",
      uzc: "Темир йўл кесишмаси. Тўхтанг ва хавфсизликка ишонч ҳосил қилинг.",
      ru: "Железнодорожный переезд. Остановитесь и убедитесь в безопасности.",
    },
    timeLimitSeconds: 60,
    maxSpeedKmh: 20,
    maxPenaltyAllowed: 20,
    hasBarrier: true,
    startX: 410,
    startY: 85,
    startRotation: Math.PI,
    targetX: 310,
    targetY: 85,
    sensorZone: { minX: 290, maxX: 420, minY: 60, maxY: 130 },
    stopLines: [{ x1: 360, y1: 65, x2: 360, y2: 105 }],
    helperPath: [
      { x: 410, y: 85 },
      { x: 360, y: 85 },
      { x: 310, y: 85 },
    ],
  },
  {
    number: 9,
    code: "ACCELERATION_STRIP",
    title: {
      uzl: "9. Tezlashish yo'lagi va tormozlash",
      uzc: "9. Тезлашиш йўлаги ва тормозлаш",
      ru: "9. Полоса разгона и торможение",
    },
    description: {
      uzl: "Tezlikni 30-40 km/soatgacha oshiring va belgilangan to'xtash zonasida ravon to'xtang.",
      uzc: "Тезликни 30-40 км/соатгача оширинг ва белгиланган тўхташ зонасида равон тўхтанг.",
      ru: "Разгонитесь до 30-40 км/ч и плавно остановитесь в обозначенной зоне остановки.",
    },
    instructorGuide: {
      uzl: "Tezlanish yo'lagi. Gazni bosing va belgilangan zonada to'xtang.",
      uzc: "Тезланиш йўлаги. Газни босинг ва белгиланган зонада тўхтанг.",
      ru: "Полоса разгона. Наберите скорость и остановитесь в обозначенном створе.",
    },
    timeLimitSeconds: 50,
    maxSpeedKmh: 40,
    maxPenaltyAllowed: 20,
    startX: 300,
    startY: 85,
    startRotation: Math.PI,
    targetX: 190,
    targetY: 85,
    sensorZone: { minX: 170, maxX: 310, minY: 60, maxY: 130 },
    helperPath: [
      { x: 300, y: 85 },
      { x: 245, y: 85 },
      { x: 190, y: 85 },
    ],
    stopLines: [{ x1: 205, y1: 65, x2: 205, y2: 105 }],
  },
  {
    number: 10,
    code: "EMERGENCY_STOP",
    title: {
      uzl: "10. Avariya holatida to'xtash",
      uzc: "10. Авария ҳолатида тўхташ",
      ru: "10. Аварийная остановка",
    },
    description: {
      uzl: "Signal berilganda zudlik bilan avariya chirog'ini yoqib xavfsiz to'xtang.",
      uzc: "Сигнал берилганда зудлик билан авария чироғини ёқиб хавфсиз тўхтанг.",
      ru: "По сигналу немедленно включите аварийную световую сигнализацию и безопасно остановитесь.",
    },
    instructorGuide: {
      uzl: "Diqqat! Avariya to'xtashi. Avariya chirog'ini yoqib to'xtang!",
      uzc: "Диққат! Авария тўхташи. Авария чироғини ёқиб тўхтанг!",
      ru: "Внимание! Аварийная остановка. Включите аварийку и остановитесь!",
    },
    timeLimitSeconds: 40,
    maxSpeedKmh: 20,
    maxPenaltyAllowed: 20,
    startX: 180,
    startY: 110,
    startRotation: Math.PI / 2,
    targetX: 120,
    targetY: 190,
    sensorZone: { minX: 100, maxX: 200, minY: 90, maxY: 210 },
    helperPath: [
      { x: 180, y: 110 },
      { x: 160, y: 150 },
      { x: 120, y: 190 },
    ],
  },
  {
    number: 11,
    code: "PARALLEL_PARKING",
    title: {
      uzl: "11. Parallel to'xtab turish (Parkovka)",
      uzc: "11. Параллель тўхтаб туриш (Парковка)",
      ru: "11. Параллельная парковка задним ходом",
    },
    description: {
      uzl: "Orqa uzatmada ikki to'siq orasiga parallel joylashing. Chiziqlarni bosmang.",
      uzc: "Орқа узатмада икки тўсиқ орасига параллель жойлашинг. Чизиқларни босманг.",
      ru: "Въедьте задним ходом между двумя препятствиями и припаркуйтесь параллельно краю проезжей части.",
    },
    instructorGuide: {
      uzl: "Parallel parkovka. Rulni to'liq buring va orqa bilan joylashing.",
      uzc: "Параллель парковка. Рулни тўлиқ буринг ва орқа билан жойлашинг.",
      ru: "Параллельная парковка. Выверните руль и аккуратно паркуйтесь задним ходом.",
    },
    timeLimitSeconds: 90,
    maxSpeedKmh: 10,
    maxPenaltyAllowed: 20,
    startX: 110,
    startY: 210,
    startRotation: Math.PI / 2,
    targetX: 65,
    targetY: 330,
    sensorZone: { minX: 50, maxX: 130, minY: 190, maxY: 340 },
    cones: [
      { x: 65, y: 240, radius: 6 },
      { x: 95, y: 240, radius: 6 },
      { x: 65, y: 310, radius: 6 },
      { x: 95, y: 310, radius: 6 },
    ],
    helperPath: [
      { x: 110, y: 210 },
      { x: 110, y: 270 },
      { x: 80, y: 310 },
    ],
  },
  {
    number: 12,
    code: "FINISH",
    title: {
      uzl: "12. Harakatni yakunlash (FINISH)",
      uzc: "12. Ҳаракатни якунлаш (ФИНИШ)",
      ru: "12. Окончание движения (ФИНИШ)",
    },
    description: {
      uzl: "FINISH chizig'ida to'xtang, uzatmani 'P'ga qo'ying, ruchnikni torting va dvigatelni o'chiring.",
      uzc: "ФИНИШ чизиғида тўхтанг, узатмани 'P'га қўйинг, ручникни тортинг ва двигателни ўчиринг.",
      ru: "Остановитесь на линии ФИНИШ, переведите селектор в 'P', затяните ручник и заглушите двигатель.",
    },
    instructorGuide: {
      uzl: "Finish chizig'i. To'xtang, uzatmani P ga qo'ying va ruchnikni torting.",
      uzc: "Финиш чизиғи. Тўхтанг, узатмани P га қўйинг ва ручникни тортинг.",
      ru: "Линия финиша. Остановитесь, переведите на паркинг и затяните ручник.",
    },
    timeLimitSeconds: 45,
    maxSpeedKmh: 15,
    maxPenaltyAllowed: 20,
    startX: 65,
    startY: 340,
    startRotation: Math.PI / 2,
    targetX: 60,
    targetY: 430,
    sensorZone: { minX: 40, maxX: 90, minY: 330, maxY: 450 },
    stopLines: [{ x1: 45, y1: 425, x2: 85, y2: 425 }],
    helperPath: [
      { x: 65, y: 340 },
      { x: 65, y: 390 },
      { x: 65, y: 425 },
    ],
  },
];
