import type { ExerciseDefinition } from "./types";

export const SIMULATOR_EXERCISES: ExerciseDefinition[] = [
  {
    number: 1,
    code: "START",
    title: {
      uzl: "1. Harakatni boshlash (START)",
      uzc: "1. Ҳаракатни бошлаш (СТАРТ)",
      ru: "1. Начало движения (СТАРТ)",
    },
    description: {
      uzl: "Xavfsizlik kamarini taqing, yaqinni yorituvchi chiroqlarni yoqing, chap burilish chirog'ini yoqib silliq qo'zg'aling.",
      uzc: "Хавфсизлик камарини тақинг, яқинни ёритувчи чироқларни ёқинг, чап бурилиш чироғини ёқиб силлиқ қўзғалинг.",
      ru: "Пристегните ремень, включите ближний свет фар, левый указатель поворота и плавно начните движение.",
    },
    instructorGuide: {
      uzl: "Xavfsizlik kamarini taqing, chiroqni yoqing va harakatni boshlang.",
      uzc: "Хавфсизлик камарини тақинг, чироқни ёқинг ва ҳаракатни бошланг.",
      ru: "Пристегните ремень безопасности, включите фары и начните движение.",
    },
    timeLimitSeconds: 60,
    maxPenaltyAllowed: 20,
    startX: 50,
    startY: 450,
    targetX: 120,
    targetY: 450,
    sensorZone: { minX: 40, maxX: 140, minY: 420, maxY: 480 },
  },
  {
    number: 2,
    code: "PEDESTRIAN_CROSSING",
    title: {
      uzl: "2. Piyodalar o'tish joyi",
      uzc: "2. Пиёдалар ўтиш жойи",
      ru: "2. Пешеходный переход",
    },
    description: {
      uzl: "Piyodalar o'tish joyi oldida STOP chizig'ini bosmasdan to'xtang va piyodaga yo'l bering.",
      uzc: "Пиёдалар ўтиш жойи олдида СТОП чизиғини босмасдан тўхтанг ва пиёдага йўл беринг.",
      ru: "Остановитесь перед стоп-линией пешеходного перехода, не наезжая на разметку, и пропустите пешехода.",
    },
    instructorGuide: {
      uzl: "Piyodalar o'tish joyiga yaqinlashyapsiz. Stop-chiziqda to'xtang.",
      uzc: "Пиёдалар ўтиш жойига яқинлашяпсиз. Стоп-чизиқда тўхтанг.",
      ru: "Приближаетесь к пешеходному переходу. Остановитесь у стоп-линии.",
    },
    timeLimitSeconds: 50,
    maxPenaltyAllowed: 20,
    startX: 140,
    startY: 450,
    targetX: 220,
    targetY: 450,
    sensorZone: { minX: 130, maxX: 230, minY: 420, maxY: 480 },
  },
  {
    number: 3,
    code: "ESTAKADA",
    title: {
      uzl: "3. Estakada (Tepalikka chiqish va to'xtash)",
      uzc: "3. Эстакада (Тепаликка чиқиш ва тўхташ)",
      ru: "3. Эстакада (Остановка и трогание на подъеме)",
    },
    description: {
      uzl: "16% qiyalikda STOP chizig'ida to'xtab, qo'l tormozini torting. Orqaga 20 sm dan ortiq sirpanmasdan harakatni davom ettiring.",
      uzc: "16% қияликда СТОП чизиғида тўхтаб, қўл тормозини тортинг. Орқага 20 см дан ортиқ сирпанмасдан ҳаракатни давом эттиринг.",
      ru: "Остановитесь на подъеме 16% у стоп-линии, включите ручник. Троньтесь без отката назад более 20 см.",
    },
    instructorGuide: {
      uzl: "Oldinda estakada. Stop-chiziqda to'xtang va qo'l tormozini torting. Orqaga sirpanmasdan qo'zg'aling.",
      uzc: "Олдинда эстакада. Стоп-чизиқда тўхтанг ва қўл тормозини тортинг. Орқага сирпанмасдан қўзғалинг.",
      ru: "Впереди эстакада. Остановитесь у стоп-линии и затяните ручник. Трогайтесь без отката.",
    },
    timeLimitSeconds: 70,
    maxPenaltyAllowed: 20,
    startX: 240,
    startY: 450,
    targetX: 340,
    targetY: 450,
    sensorZone: { minX: 230, maxX: 350, minY: 420, maxY: 480 },
  },
  {
    number: 4,
    code: "CORRIDOR_TURNS",
    title: {
      uzl: "4. 90° Burchak ostida burilishlar",
      uzc: "4. 90° Бурчак остида бурилишлар",
      ru: "4. Повороты под углом 90 градусов",
    },
    description: {
      uzl: "Tor yo'lakda o'ngga va chapga 90 gradus burilishlarni bordyur va chiziqlarni bosmasdan bajaring.",
      uzc: "Тор йўлакда ўнгга ва чапга 90 градус бурилишларни бордюр ва чизиқларни босмасдан бажаринг.",
      ru: "Выполните повороты на 90 градусов направо и налево в узком коридоре, не наезжая на разметку и бордюры.",
    },
    instructorGuide: {
      uzl: "Tor yo'lak. Tezlikni pasaytiring va rulni ehtiyotkorlik bilan buring.",
      uzc: "Тор йўлак. Тезликни пасайтиринг ва рулни эҳтиёткорлик билан буринг.",
      ru: "Узкий коридор. Снизьте скорость и аккуратно входите в повороты.",
    },
    timeLimitSeconds: 80,
    maxPenaltyAllowed: 20,
    startX: 360,
    startY: 420,
    targetX: 420,
    targetY: 340,
    sensorZone: { minX: 350, maxX: 440, minY: 320, maxY: 460 },
  },
  {
    number: 5,
    code: "SLALOM",
    title: {
      uzl: "5. Ilon izi (Zmeyka / Slalom)",
      uzc: "5. Илон изи (Змейка / Слалом)",
      ru: "5. Змейка (Слалом)",
    },
    description: {
      uzl: "5 ta to'siq konuslarini navbatma-navbat aylanib o'ting. Konuslarni urmang va zonadan chiqmang.",
      uzc: "5 та тўсиқ конусларини навбатма-навбат айланиб ўтинг. Конусларни урманг ва зонадан чиқманг.",
      ru: "Обогните 5 разметочных конусов поочередно. Не сбивайте конусы и не выезжайте за границы.",
    },
    instructorGuide: {
      uzl: "Zmeyka mashqi. Konuslarni aylanib o'ting, masofani saqlang.",
      uzc: "Змейка машқи. Конусларни айланиб ўтинг, масофани сақланг.",
      ru: "Упражнение Змейка. Огибайте конусы, соблюдая дистанцию.",
    },
    timeLimitSeconds: 75,
    maxPenaltyAllowed: 20,
    startX: 440,
    startY: 320,
    targetX: 520,
    targetY: 220,
    sensorZone: { minX: 420, maxX: 540, minY: 200, maxY: 340 },
  },
  {
    number: 6,
    code: "INTERSECTION",
    title: {
      uzl: "6. Tartibga solingan chorraha",
      uzc: "6. Тартибга солинган чорраҳа",
      ru: "6. Регулируемый перекресток",
    },
    description: {
      uzl: "Svetoforning yashil chirog'ida harakatlaning, qizil chiroqda Stop-chiziq oldida to'xtang.",
      uzc: "Светофорнинг яшил чироғида ҳаракатланинг, қизил чироқда Стоп-чизиқ олдида тўхтанг.",
      ru: "Двигайтесь на зеленый сигнал светофора, при красном остановитесь перед стоп-линией.",
    },
    instructorGuide: {
      uzl: "Chorraha oldidasiz. Svetofor signallariga qat'iy rioya qiling.",
      uzc: "Чорраҳа олдидасиз. Светофор сигналларига қатъий риоя қилинг.",
      ru: "Вы перед перекрестком. Строго соблюдайте сигналы светофора.",
    },
    timeLimitSeconds: 60,
    maxPenaltyAllowed: 20,
    startX: 530,
    startY: 200,
    targetX: 530,
    targetY: 100,
    sensorZone: { minX: 500, maxX: 560, minY: 80, maxY: 210 },
  },
  {
    number: 7,
    code: "GARAGE",
    title: {
      uzl: "7. Boksga kirish (90° Garaj)",
      uzc: "7. Боксга кириш (90° Гараж)",
      ru: "7. Въезд в бокс задним ходом (Гараж 90°)",
    },
    description: {
      uzl: "Orqa uzatma (R) bilan boksga 90 gradus burilib kiring va chegara chiziqlariga tegmang.",
      uzc: "Орқа узатма (R) билан боксга 90 градус бурилиб киринг ва чегара чизиқларига тегманг.",
      ru: "Въедьте в бокс задним ходом под углом 90 градусов, не задевая границы разметки.",
    },
    instructorGuide: {
      uzl: "Orqa uzatmani yoqing. Ko'zgularga qarab boksga kiring.",
      uzc: "Орқа узатмани ёқинг. Кўзгуларга қараб боксга киринг.",
      ru: "Включите заднюю передачу. Ориентируясь по зеркалам, заезжайте в бокс.",
    },
    timeLimitSeconds: 90,
    maxPenaltyAllowed: 20,
    startX: 510,
    startY: 90,
    targetX: 430,
    targetY: 90,
    sensorZone: { minX: 400, maxX: 530, minY: 60, maxY: 130 },
  },
  {
    number: 8,
    code: "RAILWAY_CROSSING",
    title: {
      uzl: "8. Temir yo'l kesishmasi",
      uzc: "8. Темир йўл кесишмаси",
      ru: "8. Железнодорожный переезд",
    },
    description: {
      uzl: "Shlagbaum va svetofor signallari oldida to'xtang. Poyezd o'tgach harakatni davom ettiring.",
      uzc: "Шлагбаум ва светофор сигналлари олдида тўхтанг. Поезд ўтгач ҳаракатни давом эттиринг.",
      ru: "Остановитесь перед шлагбаумом и светофором переезда. Продолжайте движение после разрешающего сигнала.",
    },
    instructorGuide: {
      uzl: "Temir yo'l kesishmasi. To'xtang va xavfsizlikka ishonch hosil qiling.",
      uzc: "Темир йўл кесишмаси. Тўхтанг ва хавфсизликка ишонч ҳосил қилинг.",
      ru: "Железнодорожный переезд. Остановитесь и убедитесь в безопасности.",
    },
    timeLimitSeconds: 60,
    maxPenaltyAllowed: 20,
    startX: 410,
    startY: 90,
    targetX: 320,
    targetY: 90,
    sensorZone: { minX: 300, maxX: 420, minY: 60, maxY: 130 },
  },
  {
    number: 9,
    code: "ACCELERATION_STRIP",
    title: {
      uzl: "9. Tezlashish yo'lagi va tormozlash",
      uzc: "9. Тезлашиш йўлаги ва тормозлаш",
      ru: "9. Полоса разгона и торможение",
    },
    description: {
      uzl: "Tezlikni 30-40 km/soatgacha oshiring va belgilangan to'xtash zonasida ravon to'xtang.",
      uzc: "Тезликни 30-40 км/соатгача оширинг ва белгиланган тўхташ зонасида равон тўхтанг.",
      ru: "Разгонитесь до 30-40 км/ч и плавно остановитесь в обозначенной зоне остановки.",
    },
    instructorGuide: {
      uzl: "Tezlanish yo'lagi. Gazni bosing va belgilangan zonada to'xtang.",
      uzc: "Тезланиш йўлаги. Газни босинг ва белгиланган зонада тўхтанг.",
      ru: "Полоса разгона. Наберите скорость и остановитесь в обозначенном створе.",
    },
    timeLimitSeconds: 50,
    maxPenaltyAllowed: 20,
    startX: 300,
    startY: 90,
    targetX: 200,
    targetY: 90,
    sensorZone: { minX: 180, maxX: 310, minY: 60, maxY: 130 },
  },
  {
    number: 10,
    code: "EMERGENCY_STOP",
    title: {
      uzl: "10. Avariya holatida to'xtash",
      uzc: "10. Авария ҳолатида тўхташ",
      ru: "10. Аварийная остановка",
    },
    description: {
      uzl: "Signal berilganda zudlik bilan avariya chirog'ini yoqib xavfsiz to'xtang.",
      uzc: "Сигнал берилганда зудлик билан авария чироғини ёқиб хавфсиз тўхтанг.",
      ru: "По сигналу немедленно включите аварийную световую сигнализацию и безопасно остановитесь.",
    },
    instructorGuide: {
      uzl: "Diqqat! Avariya to'xtashi. Avariya chirog'ini yoqib to'xtang!",
      uzc: "Диққат! Авария тўхташи. Авария чироғини ёқиб тўхтанг!",
      ru: "Внимание! Аварийная остановка. Включите аварийку и остановитесь!",
    },
    timeLimitSeconds: 40,
    maxPenaltyAllowed: 20,
    startX: 190,
    startY: 120,
    targetX: 120,
    targetY: 180,
    sensorZone: { minX: 100, maxX: 210, minY: 100, maxY: 200 },
  },
  {
    number: 11,
    code: "PARALLEL_PARKING",
    title: {
      uzl: "11. Parallel to'xtab turish (Parkovka)",
      uzc: "11. Параллель тўхтаб туриш (Парковка)",
      ru: "11. Параллельная парковка задним ходом",
    },
    description: {
      uzl: "Orqa uzatmada ikki to'siq orasiga parallel joylashing. Chiziqlarni bosmang.",
      uzc: "Орқа узатмада икки тўсиқ орасига параллель жойлашинг. Чизиқларни босманг.",
      ru: "Въедьте задним ходом между двумя препятствиями и припаркуйтесь параллельно краю проезжей части.",
    },
    instructorGuide: {
      uzl: "Parallel parkovka. Rulni to'liq buring va orqa bilan joylashing.",
      uzc: "Параллель парковка. Рулни тўлиқ буринг ва орқа билан жойлашинг.",
      ru: "Параллельная парковка. Выверните руль и аккуратно паркуйтесь задним ходом.",
    },
    timeLimitSeconds: 90,
    maxPenaltyAllowed: 20,
    startX: 110,
    startY: 210,
    targetX: 70,
    targetY: 320,
    sensorZone: { minX: 50, maxX: 140, minY: 190, maxY: 340 },
  },
  {
    number: 12,
    code: "FINISH",
    title: {
      uzl: "12. Harakatni yakunlash (FINISH)",
      uzc: "12. Ҳаракатни якунлаш (ФИНИШ)",
      ru: "12. Окончание движения (ФИНИШ)",
    },
    description: {
      uzl: "FINISH chizig'ida to'xtang, uzatmani 'P' (yoki Neytral)ga qo'ying, ruchnikni torting va dvigatelni o'chiring.",
      uzc: "ФИНИШ чизиғида тўхтанг, узатмани 'P' (ёки Нейтрал)га қўйинг, ручникни тортинг ва двигателни ўчиринг.",
      ru: "Остановитесь на линии ФИНИШ, переведите селектор в 'P' (или Нейтраль), затяните ручник и заглушите двигатель.",
    },
    instructorGuide: {
      uzl: "Finish chizig'i. To'xtang, uzatmani P ga qo'ying va ruchnikni torting.",
      uzc: "Финиш чизиғи. Тўхтанг, узатмани P га қўйинг ва ручникни тортинг.",
      ru: "Линия финиша. Остановитесь, поставьте на паркинг и затяните ручник.",
    },
    timeLimitSeconds: 45,
    maxPenaltyAllowed: 20,
    startX: 70,
    startY: 340,
    targetX: 50,
    targetY: 430,
    sensorZone: { minX: 40, maxX: 90, minY: 330, maxY: 450 },
  },
];
